name: Verify Playlist Submission

on:
  pull_request_target:
    paths:
      - 'playlist.json'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema requests

      - name: Run verification script
        id: verify
        run: python .github/scripts/verify_playlist.py
        continue-on-error: true

      - name: Check verification result
        if: steps.verify.outcome != 'success'
        run: exit 1

      - name: Debug Context Information
        run: |
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
      
      - name: Comment on PR (Success)
        if: steps.verify.outcome == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = "✅ Playlist verification passed! Your submission looks good.";
            const issueNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            console.log(`Owner: ${owner}, Repo: ${repo}, Issue Number: ${issueNumber}`);
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
              body: output
            });

      - name: Debug Context Information
        run: |
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
      

