name: Verify Playlist Submission

on:
  pull_request:
    paths:
      - 'playlist.json'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema requests

      - name: Run verification script
        id: verify
        run: python .github/scripts/verify_playlist.py
        continue-on-error: true

      - name: Sieve Manager
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const output = "${{ steps.verify.outputs.result }}";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: output
            });

      - name: Check verification result
        if: steps.verify.outcome != 'success'
        run: exit 1
